version: "3.7"

services:

  library_server:
    container_name: library_server
    build:
      dockerfile: ./deployments/docker/library_server/Dockerfile
    healthcheck:
      test:
        [
          "CMD",
          "bin/grpc_health_probe",
          "-addr=${LIBRARY_SERVER_ADDR:-:50051}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      LIBRARY_SERVER_ADDR: ${LIBRARY_SERVER_ADDR:-:50051}
      DB_USER: ${DB_USER:-librarian}
      DB_PASSWORD: ${DB_PASSWORD:-librarianpassword}
      DB_ADDR: ${DB_ADDR:-db:3306}
      DB_NAME: ${DB_NAME:-library}
      DB_CONN_MAX_LIFE_TIME_SEC: ${DB_CONN_MAX_LIFE_TIME_SEC:-15}15
      DB_CONN_MAX_IDLE_TIME_SEC: ${DB_CONN_MAX_IDLE_TIME_SEC:-5}5
      DB_MAX_OPEN_CONNNS: ${DB_MAX_OPEN_CONNNS:-150}
      DB_MAX_IDLE_CONNS: ${DB_MAX_IDLE_CONNS:-150}
    depends_on:
      db:
        condition: service_healthy
    external_links:
      - db
    ports:
      - "50051:50051"
    networks:
      - netApplication

  db:
    container_name: db
    platform: linux/amd64
    build:
      dockerfile: ./deployments/docker/mysql/Dockerfile
    environment:
      MYSQL_DATABASE: ${DB_NAME:-library}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
      MYSQL_USER: ${DB_USER:-librarian}
      MYSQL_PASSWORD: ${DB_PASSWORD:-librarianpassword}
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: mysqladmin ping -ppass
    volumes:
      - mysqlData:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - netApplication

volumes:
  mysqlData:


networks:
  netApplication:
    name: netApplication
