apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: library-server-db-data
  namespace: library-server
  labels:
    app: library-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi