apiVersion: v1
kind: Secret
metadata:
  name: library-server-secret
  namespace: library-server
  labels:
    app: library-server
type: Opaque
# immutable: true
# data:
#   DB_URI: 
stringData:
  # Migration
  DB_URI: mysql://librarian:librarianpassword@tcp(library-server-db-svc)/library?x-tls-insecure-skip-verify=false
  # Server gRPC
  DB_ADDR: library-server-db-svc
  DB_NAME: library
  DB_USER: librarian
  DB_PASSWORD: librarianpassword
  # Время жизни соединения
  DB_CONN_MAX_LIFE_TIME_SEC: "15"
  # Время ожидания в пуле
  DB_CONN_MAX_IDLE_TIME_SEC: "5"
  # Максимальное количество соединений
  DB_MAX_OPEN_CONNNS: "50"
  # Ограничение размера пула
  DB_MAX_IDLE_CONNS: "50"
---
apiVersion: v1
kind: Secret
metadata:
  name: library-server-db-secret
  namespace: library-server
  labels:
    app: library-server
type: Opaque
stringData:
  # DB
  MYSQL_DATABASE: library
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_USER: librarian
  MYSQL_PASSWORD: librarianpassword
  

