apiVersion: v1
kind: Secret
metadata:
  name: library-server-secret
  namespace: library-server
  labels:
    app: library-server
type: Opaque
# immutable: true
# data:
#   DB_URI: 
stringData:
  # Migration
  DB_URI: mysql://librarian:librarianpassword@tcp(library-server-db-svc)/library?x-tls-insecure-skip-verify=false
  # Server gRPC
  DB_ADDR: library-server-db-svc
  DB_NAME: library
  DB_USER: librarian
  DB_PASSWORD: librarianpassword
---
apiVersion: v1
kind: Secret
metadata:
  name: library-server-db-secret
  namespace: library-server
  labels:
    app: library-server
type: Opaque
stringData:
  # DB
  MYSQL_DATABASE: library
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_USER: librarian
  MYSQL_PASSWORD: librarianpassword
  

